# Each field formatter needs schema for the settings.
field.formatter.settings.entity_reference_table:
  type: mapping
  label: 'Entity reference field formatter settings.'
  mapping:
    view_mode:
      type: string
      label: 'View Mode'
    show_entity_label:
      type: boolean
      label: 'Show Entity Label'
    empty_cell_value:
      type: string
      label: 'Empty Cell Value'
    hide_header:
      type: string
      label: 'Hide Header'
